
exports.up = function(knex, Promise) {
  var query = ' CREATE VIEW vw_objeto_acesso AS  ';
  query += 'SELECT  ';
  query += '  "pel_conteudo_acesso"."id"                 AS "id"  ';
  query += ',"pel_conteudo_acesso"."dt_criacao"          AS  ';
  query += '"dt_criacao"  ';
  query += ',"pel_conteudo_acesso"."praticaEducativaId"  AS  ';
  query += '"praticaEducativaId"  ';
  query += ',"pel_conteudo_acesso"."usuarioId"           AS "usuarioId"  ';
  query += ',"pel_conteudo_acesso"."objetoEducacionalId" AS "objeto"  ';
  query += 'FROM  ';
  query += '"pel_conteudo_acesso"  ';
  query += 'UNION  ';
  query += 'ALL  ';
  query += 'SELECT  ';
  query += '"pel_conteudo_acesso"."id"                   AS "id"  ';
  query += ',"pel_conteudo_acesso"."dt_criacao"            AS  ';
  query += '"dt_criacao"  ';
  query += ',"pel_conteudo_acesso"."praticaEducativaId"    AS  ';
  query += '"praticaEducativaId"  ';
  query += ',"pel_conteudo_acesso"."usuarioId"             AS  ';
  query += '"usuarioId"  ';
  query += ',"pel_conteudo_acesso"."objetoInformacionalId" AS "objeto"  ';
  query += 'FROM  ';
  query += '"pel_conteudo_acesso"  ';
  query += 'WHERE  ';
  query += '("pel_conteudo_acesso"."objetoInformacionalId" IS NOT NULL)  ';
  query += 'UNION  ';
  query += 'ALL  ';
  query += 'SELECT  ';
  query += '"pel_conteudo_acesso"."id"                   AS "id"  ';
  query += ',"pel_conteudo_acesso"."dt_criacao"            AS  ';
  query += '"dt_criacao"  ';
  query += ',"pel_conteudo_acesso"."praticaEducativaId"    AS  ';
  query += '"praticaEducativaId"  ';
  query += ',"pel_conteudo_acesso"."usuarioId"             AS  ';
  query += '"usuarioId"  ';
  query += ',"pel_conteudo_acesso"."elementoEducacionalId" AS "objeto"  ';
  query += 'FROM  ';
  query += '"pel_conteudo_acesso"  ';
  query += 'WHERE  ';
  query += '("pel_conteudo_acesso"."elementoEducacionalId" IS NOT NULL)  ';
  query += 'UNION  ';
  query += 'ALL  ';
  query += 'SELECT  ';
  query += '"pe"."id"                  AS "id"  ';
  query += ',"pe"."dt_criacao"           AS "dt_criacao"  ';
  query += ',"pe"."id"                   AS "praticaEducativaId"  ';
  query += ',"pe"."usuarioId"            AS "usuarioId  ';
  query += ',"pe"."objetoAprendizagemId" AS "objeto"  ';
  query += 'FROM  ';
  query += '("pel_pratica_educativa" "pe"  ';
  query += 'JOIN "pel_objeto_aprendizagem" "ao"  ';
  query += 'ON((("pe"."objetoAprendizagemId" = "ao"."id")  ';
  query += 'AND ("ao"."objetoAprendizagemTipoId" = 4))));  ';
  query += '  ';


  var queryView = ' CREATE ';
  queryView += ' OR ';
  queryView += ' REPLACE ';
  queryView += ' VIEW dados_desnomalizado AS ';
  queryView += ' SELECT ';
  queryView += ' "woa"."id"                                                       AS "id" ';
  queryView += ' ,"woa"."dt_criacao"                                                AS ';
  queryView += ' "dt_acesso" ';
  queryView += ' ,"woa"."praticaEducativaId"                                        AS ';
  queryView += ' "praticaEducativaId" ';
  queryView += ' ,( ';
  queryView += ' CASE ';
  queryView += ' WHEN ("pe"."progresso_percentual" BETWEEN 0 ';
  queryView += ' AND 24) ';
  queryView += ' THEN \'0% até 24%\' ';
  queryView += ' WHEN ("pe"."progresso_percentual" BETWEEN 25 ';
  queryView += ' AND 74) ';
  queryView += ' THEN \'25% até 74%\' ';
  queryView += ' WHEN ("pe"."progresso_percentual" BETWEEN 75 ';
  queryView += ' AND 99) ';
  queryView += ' THEN \'75% até 99%\' ';
  queryView += ' WHEN ("pe"."progresso_percentual" = 100) ';
  queryView += ' THEN \'100%\' ';
  queryView += ' END)                                                         AS "conclusao" ';
  queryView += ' ,( ';
  queryView += ' CASE ';
  queryView += ' WHEN (CAST("pe"."dt_criacao" AS TIME) BETWEEN \'00:00:00\' ';
  queryView += ' AND \'05:59:59\') ';
  queryView += ' THEN \'MADRUGADA\' ';
  queryView += ' WHEN (CAST("pe"."dt_criacao" AS TIME) BETWEEN \'06:00:00\' ';
  queryView += ' AND \'11:59:59\') ';
  queryView += ' THEN \'MANHÃ\' ';
  queryView += ' WHEN (CAST("pe"."dt_criacao" AS TIME) BETWEEN \'12:00:00\' ';
  queryView += ' AND \'17:59:59\') ';
  queryView += ' THEN \'TARDE\' ';
  queryView += ' WHEN (CAST("pe"."dt_criacao" AS TIME) BETWEEN \'18:00:00\' ';
  queryView += ' AND \'23:59:59\') ';
  queryView += ' THEN \'NOITE\' ';
  queryView += ' END)                                                         AS "periodo" ';
  queryView += ' ,str_to_date(date_format("pe"."dt_criacao",\'%m/%d/%Y\'),\'%m/%d/%Y\') AS "data" ';
  queryView += ' ,"woa"."usuarioId"                                                 AS ';
  queryView += ' "usuarioId" ';
  queryView += ' ,date_format("pu"."created",\'%d/%m/%Y\')                            AS ';
  queryView += ' "dt_cadastro" ';
  queryView += ' ,"pu"."nome"                                                       AS "nome" ';
  queryView += ' ,"pu"."sexo"                                                       AS "sexo" ';
  queryView += ' ,"pu"."dt_nascimento"                                              AS ';
  queryView += ' "dt_nascimento" ';
  queryView += ' ,YEAR(from_days((to_days(now()) - to_days("pu"."dt_nascimento")))) ';
  queryView += ' AS "idade" ';
  queryView += ' ,"est"."sigla"                                                     AS ';
  queryView += ' "estado" ';
  queryView += ' ,"muni"."nome"                                                     AS ';
  queryView += ' "municipio" ';
  queryView += ' ,"woa"."objeto"                                                    AS ';
  queryView += ' "objeto" ';
  queryView += ' ,"oa"."titulo"                                                     AS ';
  queryView += ' "titulo" ';
  queryView += ' ,"oat"."id"                                                        AS ';
  queryView += ' "tipo_id" ';
  queryView += ' ,"oat"."nome"                                                      AS "tipo" ';
  queryView += ' ,"oam"."nome"                                                      AS ';
  queryView += ' "midia" ';
  queryView += ' FROM ';
  queryView += ' (((((((("vw_objeto_acesso" "woa" ';
  queryView += ' JOIN "pel_objeto_aprendizagem" "oa" ';
  queryView += ' ON(("woa"."objeto" = "oa"."id"))) ';
  queryView += ' JOIN "pel_objeto_aprendizagem_tipo" "oat" ';
  queryView += ' ON(("oat"."id" = "oa"."objetoAprendizagemTipoId"))) ';
  queryView += ' JOIN "pel_objeto_aprendizagem_midia" "oam" ';
  queryView += ' ON(("oam"."id" = "oa"."objetoAprendizagemMidiaId"))) ';
  queryView += ' JOIN "pel_pratica_educativa" "pe" ';
  queryView += ' ON(("pe"."id" = "woa"."praticaEducativaId"))) ';
  queryView += ' JOIN "pel_usuario" "pu" ';
  queryView += ' ON(("pu"."id" = "woa"."usuarioId"))) ';
  queryView += ' LEFT JOIN "pel_endereco" "ende" ';
  queryView += ' ON(("pu"."enderecoId" = "ende"."id"))) ';
  queryView += ' LEFT JOIN "pel_municipio" "muni" ';
  queryView += ' ON(("muni"."id" = "ende"."municipioId"))) ';
  queryView += ' LEFT JOIN "pel_estado" "est" ';
  queryView += ' ON(("muni"."estadoId" = "est"."id")))  ';
  queryView += ' '

  knex.raw(query).then(function(err1, result1) {
    knex.raw(queryView).then(function(err2, result2) {
      assert.isNotError(err);
    });
    assert.isNotError(err);
  });
};

exports.down = function(knex, Promise) {

};
